swagger: "2.0"
info:
  version: 1.0.0
  title: 中間DBプロジェクト API定義
  description: |
    - 旅ワンやエージェントに公開するオープンAPI
schemes:
  - http
  - https
host: middle-db
basePath: /public_api/
tags:
  - name: Idemptency
    description: 冪等性
  - name: "Commodity"
    description: 商材系
  - name: "Plan"
    description: コース計d
  - name: "Reserve"
    description: 予約に関するAPI群
    # externalDocs:
    #   description: "BBBBBBBBBB"
    #   url: "http://fugafuga"

paths:
  /idempotency:
    get:
      tags:
        - Idemptency
      summary: 冪等キー取得(生成)
      produces:
        - application/json
      responses:
        200:
          description: 冪等キー取得

    post:
      tags:
        - Idemptency
      consumes:
        - application/json
      responses:
        200:
          description: 冪等キー取得

  /articles:
    get:
      summary: 記事一覧を取得
      tags:
        - Commodity
      responses:
        200:
          description: Hello World
          schema:
            type: array
            example:
              [
                {
                  id: ef304778ada8a6,
                  title: ReactNative@v0.63で追加されたPressableが地味にすごい,
                  link: https://zenn.dev/nekoniki/articles/ef304778ada8a6,
                },
              ]

  /articles/{id}:
    get:
      summary: 指定した記事の詳細を取得
      tags:
        - Article
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string
                example: ef304778ada8a6
              author:
                type: string
                example: ネコニキ
              title:
                type: string
                example: ReactNative@v0.63で追加されたPressableが地味にすごい
              link:
                type: string
                example: https://zenn.dev/nekoniki/articles/ef304778ada8a6
      parameters:
        - name: id
          in: header
          type: string
          required: true

  /books/{id}:
    delete:
      summary: 指定した書籍の削除
      tags:
        - Book
      produces:
        - application/x-www-form-urlencoded
      consumes:
        - application/text/plain
      responses:
        200:
          description: 削除完了時のレスポンス
      parameters:
        - name: id
          in: header
          type: string
          required: true
